# Generated by Django 2.0 on 2019-02-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productmanager', '0001_initial'),
        ('receptmanager', '0001_initial'),
        ('campaign', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rx_data', to='receptmanager.ReceptManager', verbose_name='Эмийн санч'),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='related_campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_data', to='campaign.Campaign', verbose_name='Хамаарах хөтөлбөр'),
        ),
        migrations.AddField(
            model_name='campaignaxis',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_axis', to='campaign.Campaign', verbose_name='Хамаарах хөтөлбөр'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_campaigns', to='productmanager.ProductManager', verbose_name='Продакт менежер'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='top_advice',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='post.AdvicePost', verbose_name='Топ зөвөлгөө'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='top_post',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='post.Post', verbose_name='Топ материал'),
        ),
        migrations.AddIndex(
            model_name='campaigndata',
            index=models.Index(fields=['related_campaign', 'manager'], name='campaign_ca_related_f5e5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndata',
            index=models.Index(fields=['related_campaign'], name='campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndata',
            index=models.Index(fields=['manager'], name='manager_idx'),
        ),
    ]
