# Generated by Django 2.0 on 2019-02-17 11:46

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default='', max_length=100, unique=True, verbose_name='Token')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='Broadcast')),
                ('type', models.IntegerField(default=0, verbose_name='Төрөл')),
                ('point', models.BigIntegerField(default=0, verbose_name='Тоон утга')),
                ('read', models.BooleanField(default=False, verbose_name='Уншсан эсэх')),
                ('title', models.CharField(default='', max_length=500, verbose_name='Title')),
                ('content', models.CharField(default='', max_length=500, verbose_name='Content')),
                ('url', models.CharField(default='https://monos.workplace.com/chat/t/2018267958393888', max_length=500, verbose_name='Redirect URL')),
                ('is_shared', models.BooleanField(default=False, verbose_name='is shared?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceptManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(default='', help_text='Бүтэн нэр автоматаар үүснэ', max_length=100, verbose_name='Бүтэн нэр')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Нэр')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Овог')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Нэвтрэх нэр')),
                ('title', models.CharField(default='', help_text='Албан тушаал автоматаар үүснэ', max_length=150, verbose_name='Албан тушаал')),
                ('department', models.CharField(default='', help_text='Газар хэлтэс автоматаар үүснэ', max_length=250, verbose_name='Газар/хэлтэс')),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Имэйл')),
                ('role', models.IntegerField(choices=[(0, 'Менежер'), (1, 'Хяналтын менежер')], default=0, verbose_name='Төрөл')),
                ('facebook_id', models.CharField(blank=True, default='', max_length=80, verbose_name='Фэйсбүүк ID')),
                ('facebook_id_workspace', models.CharField(blank=True, default='', max_length=80, verbose_name='Фэйсбүүк ID(Workspace)')),
                ('facebook_id_messenger', models.CharField(blank=True, default='', max_length=80, unique=True, verbose_name='Фэйсбүүк ID(Messenger Bot)')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Утасны дугаар')),
                ('address', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Гэрийн хаяг')),
                ('facebook', models.CharField(blank=True, default='', max_length=80, verbose_name='Фэйсбүүк хаяг')),
                ('about', models.TextField(blank=True, default='', max_length=144, verbose_name='Тухай')),
                ('avatar_link', models.CharField(blank=True, default='', max_length=500, verbose_name='Зураг')),
                ('manager_url', models.CharField(editable=False, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('rx_xp', models.BigIntegerField(default=0, verbose_name='XP')),
                ('rx_level', models.IntegerField(default=1, verbose_name='Level')),
                ('rx_daily_xp', models.IntegerField(default=0, verbose_name='Өнөөдөр цуглуулсан XP')),
                ('rx_weekly_xp', models.IntegerField(default=0, verbose_name='Энэ долоо хоногт цуглуулсан XP')),
                ('rx_monthly_xp', models.IntegerField(default=0, verbose_name='Энэ сард цуглуулсан XP')),
                ('rx_coin_collected', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн цуглуулсан зоос')),
                ('rx_coin_consumed', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн зарцуулсан зоос')),
                ('rx_coin_balance', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн үлдсэн зоос')),
                ('rx_coin_daily_consumption', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн өдөрт зарцуулсан зоос')),
                ('rx_coin_weekly_consumption', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн долоо хоногт зарцуулсан зоос')),
                ('rx_coin_monthly_consumption', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн сард хоногт зарцуулсан зоос')),
                ('rx_xp_on_comment', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн комментоос цуглуулсан XP')),
                ('rx_xp_on_advice', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн зөвлөгөөнөөс цуглуулсан XP')),
                ('rx_xp_on_test', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн тестнээс цуглуулсан XP')),
                ('rx_xp_on_like', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн лайкаас цуглуулсан XP')),
                ('rx_xp_on_share', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн шэйрээс цуглуулсан XP')),
                ('should_refetch', models.BooleanField(default=False, verbose_name='Мэдээлэл дахин татах')),
                ('location', models.CharField(default='', help_text='Салбар автоматаар үүснэ', max_length=250, verbose_name='Салбар')),
                ('badge_like', models.BooleanField(default=True, verbose_name='Badge like')),
                ('badge_test', models.BooleanField(default=True, verbose_name='Badge test')),
                ('badge_comment', models.BooleanField(default=True, verbose_name='Badge comment')),
                ('badge_advice', models.BooleanField(default=True, verbose_name='Badge advice')),
                ('badge_share', models.BooleanField(default=True, verbose_name='Badge share')),
                ('bum_coin_collected', models.BigIntegerField(default=0, verbose_name='Борлуулалтаас цуглуулсан мойл')),
                ('bum_coin_collected_daily', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн өдөрт цуглуулсан зоос /Buman IT/')),
                ('bum_coin_collected_weekly', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн 7 хоногт цуглуулсан зоос /Buman IT/')),
                ('bum_coin_collected_monthly', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн сард цуглуулсан зоос /Buman IT/')),
                ('camp_coin_collected', models.BigIntegerField(default=0, verbose_name='Сургалтаас цуглуулсан мойл')),
                ('camp_coin_collected_daily', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн өдөрт цуглуулсан зоос /Campaign/')),
                ('camp_coin_collected_weekly', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн 7 хоногт цуглуулсан зоос /Campaign/')),
                ('camp_coin_collected_monthly', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн сард цуглуулсан зоос /Campaign/')),
                ('manager_type', models.IntegerField(choices=[(0, 'Эмийн санч'), (1, 'Гоо сайханч')], default=None, verbose_name='Менежерийн төрөл')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptmanagers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Эмийн санч (RX)',
                'verbose_name_plural': 'Эмийн санчид (RX)',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='ReceptManagerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=None, verbose_name='Огноо')),
                ('rx_xp', models.BigIntegerField(default=0, verbose_name='XP')),
                ('rx_level', models.IntegerField(default=0, verbose_name='Level')),
                ('rx_weekly_xp', models.IntegerField(default=0, verbose_name='Энэ долоо хоногт цуглуулсан XP')),
                ('rx_coin_collected', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн цуглуулсан зоос')),
                ('bum_coin_collected', models.BigIntegerField(default=0, verbose_name='Борлуулалтаас цуглуулсан мойл')),
                ('rx_coin_consumed', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн зарцуулсан зоос')),
                ('rx_coin_balance', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн үлдсэн зоос')),
                ('rx_coin_weekly_consumption', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн долоо хоногт зарцуулсан зоос')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager_data', to='receptmanager.ReceptManager', verbose_name='Эмийн санч')),
            ],
            options={
                'verbose_name': 'Эмийн санчийн дата (RX)',
                'verbose_name_plural': 'Эмийн санчидын дата (RX)',
                'ordering': ['manager_id', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ReceptManagerDataDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=None, verbose_name='Огноо')),
                ('rx_xp', models.BigIntegerField(default=0, verbose_name='XP')),
                ('rx_level', models.IntegerField(default=0, verbose_name='Level')),
                ('rx_daily_xp', models.IntegerField(default=0, verbose_name='Өнөөдөр цуглуулсан XP')),
                ('rx_coin_collected', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн цуглуулсан зоос')),
                ('bum_coin_collected', models.BigIntegerField(default=0, verbose_name='Борлуулалтаас цуглуулсан мойл')),
                ('rx_coin_consumed', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн зарцуулсан зоос')),
                ('rx_coin_balance', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн үлдсэн зоос')),
                ('rx_coin_daily_consumption', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн өдөрт зарцуулсан зоос')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager_data_daily', to='receptmanager.ReceptManager', verbose_name='Эмийн санч')),
            ],
            options={
                'verbose_name': 'Эмийн санчийн дата (RX)',
                'verbose_name_plural': 'Эмийн санчидын дата (RX)',
                'ordering': ['manager_id', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ReceptManagerDataMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(default=2017, verbose_name='Он')),
                ('month', models.IntegerField(default=2, verbose_name='Сар')),
                ('rx_xp', models.BigIntegerField(default=0, verbose_name='XP')),
                ('rx_level', models.IntegerField(default=0, verbose_name='Level')),
                ('rx_monthly_xp', models.IntegerField(default=0, verbose_name='Энэ долоо хоногт цуглуулсан XP')),
                ('rx_coin_collected', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн цуглуулсан зоос')),
                ('bum_coin_collected', models.BigIntegerField(default=0, verbose_name='Борлуулалтаас цуглуулсан мойл')),
                ('rx_coin_consumed', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн зарцуулсан зоос')),
                ('rx_coin_balance', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн үлдсэн зоос')),
                ('rx_coin_monthly_consumption', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн долоо хоногт зарцуулсан зоос')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager_data_monthly', to='receptmanager.ReceptManager', verbose_name='Эмийн санч')),
            ],
            options={
                'verbose_name': 'Эмийн санчийн дата (RX)',
                'verbose_name_plural': 'Эмийн санчидын дата (RX)',
                'ordering': ['manager_id', '-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('collected_coin', models.BigIntegerField(default=0, verbose_name='Хэрэглэгчийн цуглуулсан зоос')),
                ('collected_date', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sales', to='campaign.Campaign')),
                ('campaign_axis', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_axis_sales', to='campaign.CampaignAxis')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager_sales', to='receptmanager.ReceptManager', verbose_name='Эмийн санч')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager_data_notification', to='receptmanager.ReceptManager', verbose_name='Эмийн санч'),
        ),
        migrations.AddField(
            model_name='device',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager_device', to='receptmanager.ReceptManager', verbose_name='Эмийн санч'),
        ),
        migrations.CreateModel(
            name='BeauticianManager',
            fields=[
            ],
            options={
                'verbose_name': 'Гоо сайханч (RX)',
                'verbose_name_plural': 'Гоо сайханчид (RX)',
                'ordering': ['fullname'],
                'proxy': True,
                'indexes': [],
            },
            bases=('receptmanager.receptmanager',),
        ),
    ]
