# Generated by Django 2.0 on 2019-02-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20190217_1146'),
        ('receptmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('collected_coin', models.DecimalField(decimal_places=2, default=None, max_digits=65, verbose_name='Хэрэглэгчийн цуглуулсан зоос')),
                ('collected_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=None, max_digits=65, verbose_name='Борлуулалтын тоо ширхэг')),
                ('campaign_axis', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_axis_sales_log', to='campaign.CampaignAxis')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager_sales_log', to='receptmanager.ReceptManager', verbose_name='Эмийн санч')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
