# Generated by Django 2.0.7 on 2019-02-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptmanager', '0004_saleslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=65, verbose_name='Борлуулалтын тоо ширхэг'),
        ),
    ]
