# Generated by Django 2.2.6 on 2019-12-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptmanager', '0006_merge_20191019_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptmanager',
            name='bum_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Борлуулалтаас цуглуулсан мойл'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='bum_coin_collected_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн өдөрт цуглуулсан зоос /Buman IT/'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='bum_coin_collected_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн сард цуглуулсан зоос /Buman IT/'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='bum_coin_collected_weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн 7 хоногт цуглуулсан зоос /Buman IT/'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='camp_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Сургалтаас цуглуулсан мойл'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='camp_coin_collected_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн өдөрт цуглуулсан зоос /Campaign/'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='camp_coin_collected_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн сард цуглуулсан зоос /Campaign/'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='camp_coin_collected_weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн 7 хоногт цуглуулсан зоос /Campaign/'),
        ),
    ]
