# Generated by Django 2.2.6 on 2019-12-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptmanager', '0007_auto_20191203_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptmanager',
            name='rx_coin_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн үлдсэн зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='rx_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн цуглуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='rx_coin_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='rx_coin_daily_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн өдөрт зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='rx_coin_monthly_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн сард хоногт зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanager',
            name='rx_coin_weekly_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн долоо хоногт зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdata',
            name='bum_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Борлуулалтаас цуглуулсан мойл'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdata',
            name='rx_coin_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн үлдсэн зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdata',
            name='rx_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн цуглуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdata',
            name='rx_coin_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdata',
            name='rx_coin_weekly_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн долоо хоногт зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatadaily',
            name='bum_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Борлуулалтаас цуглуулсан мойл'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatadaily',
            name='rx_coin_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн үлдсэн зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatadaily',
            name='rx_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн цуглуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatadaily',
            name='rx_coin_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatadaily',
            name='rx_coin_daily_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн өдөрт зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatamonthly',
            name='bum_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Борлуулалтаас цуглуулсан мойл'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatamonthly',
            name='rx_coin_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн үлдсэн зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatamonthly',
            name='rx_coin_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн цуглуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatamonthly',
            name='rx_coin_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='receptmanagerdatamonthly',
            name='rx_coin_monthly_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн долоо хоногт зарцуулсан зоос'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='collected_coin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='Хэрэглэгчийн цуглуулсан зоос'),
        ),
    ]
