# Generated by Django 2.2.6 on 2019-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptmanager', '0008_auto_20191203_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='collected_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
