# Generated by Django 2.2.6 on 2019-12-13 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptmanager', '0009_auto_20191213_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='collected_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
