# Generated by Django 2.0 on 2019-02-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptmanager', '0001_initial'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvicePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('post_name', models.TextField(blank=True, default='', verbose_name='Гарчиг')),
                ('facebook_id', models.BigIntegerField(default=0, unique=True, verbose_name='Фэйсбүүк ID')),
                ('group_id', models.CharField(default='154243908530765', max_length=50, verbose_name='Груп ID')),
                ('like_count', models.IntegerField(default=0, verbose_name='Лайкын тоо')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Комментын тоо')),
                ('post_url', models.URLField(default='', max_length=500, verbose_name='Постын URL')),
                ('image_url', models.URLField(default='', max_length=500, verbose_name='Постын зургийн URL')),
                ('related_campaing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='advice_posts', to='campaign.Campaign', verbose_name='Хамааралтай хөтөлбөр')),
                ('related_manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='advice_posts', to='receptmanager.ReceptManager', verbose_name='Зөвөлгөөг оруулсан менежер')),
            ],
            options={
                'verbose_name': 'Зөвөлгөө',
                'verbose_name_plural': '2. Зөвөлгөөнүүд',
                'ordering': ['-related_campaing_id', '-like_count'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('post_url', models.URLField(max_length=500, verbose_name='Постын URL')),
                ('post_name', models.TextField(blank=True, default='', verbose_name='Гарчиг')),
                ('facebook_id', models.BigIntegerField(blank=True, default=0, unique=True, verbose_name='Фэйсбүүк ID')),
                ('like_count', models.IntegerField(default=0, verbose_name='Лайкын тоо')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Комментын тоо')),
                ('image_url', models.URLField(default='', max_length=500, verbose_name='Постын зургийн URL')),
                ('refetch_data', models.BooleanField(default=False, verbose_name='Постын мэдээ дахин татах')),
                ('group_id', models.CharField(default='154243908530765', max_length=50, verbose_name='Груп ID')),
                ('related_campaing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campaign.Campaign', verbose_name='Хамааралтай хөтөлбөр')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': '1. Постууд',
                'ordering': ['-related_campaing_id', '-like_count'],
            },
        ),
    ]
