# Generated by Django 2.0 on 2019-02-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(default='', max_length=200, verbose_name='Тестийн нэр')),
                ('is_active', models.BooleanField(default=False, verbose_name='Идэвхитэй эсэх')),
                ('related_campaign', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_test', to='campaign.Campaign', verbose_name='Хамаарах хөтөлбөр')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тестүүд',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OnlineTestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('short_answer', models.CharField(default='', max_length=1, verbose_name='Богино хариулт')),
                ('full_answer', models.TextField(default='', verbose_name='Бүтэн хариулт')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Зөв хариулт эсэх')),
            ],
            options={
                'verbose_name': 'Хариулт',
                'verbose_name_plural': 'Хариултууд',
                'ordering': ['short_answer', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OnlineTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Дугаар')),
                ('question', models.CharField(default='', max_length=200, verbose_name='Асуулт')),
                ('related_test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onlinetest.OnlineTest', verbose_name='Хамаарах тест')),
            ],
            options={
                'verbose_name': 'Асуулт',
                'verbose_name_plural': 'Асуултууд',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='onlinetestanswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onlinetest.OnlineTestQuestion'),
        ),
    ]
