# Generated by Django 2.0 on 2019-02-17 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptmanager', '0001_initial'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonosControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('control_name', models.CharField(default='Ерөнхий удирдлага', max_length=200, verbose_name='Нэр')),
                ('regenerate_campaign_data', models.BooleanField(default=False, verbose_name='Хөтөлбөрийн өгөгдөл дахин үүсгэх')),
                ('fetch_campaign_post_data', models.BooleanField(default=False, verbose_name='Хөтөлбөртэй холбоотой постын мэдээ татах')),
                ('clean_current_campaign', models.BooleanField(default=False, verbose_name='Идэвхтэй хөтөлбөрийг арилгах')),
                ('store_status', models.BooleanField(default=True, verbose_name='Дэлгүүрийн төлөв')),
                ('group_id', models.CharField(default='154243908530765', max_length=100, verbose_name='Груп ID')),
                ('group_token', models.CharField(default='DQVJ1SWtIWlVUZA0JrNjd6UXJ0SXFuOTRYRUgwTWd3SU5aZAnkyeDNhQXR1eDJZAdWdhbGZASTUt2T0hXblhZAX0h5cVRmOEZAyU2tsZAVgwSVJGVk5lYVRVSV9WNVppa0ZAIVjRJWk9kZA1B3THVkOTVPdWNjeTd4NlFwY3ZA6a1ZApY0pDbTNEbW1wTDVWSFViVzl5UkZArWl9qWmxGN0Fia3RvdFNqVzQ1NGpFN1ZA1LTl5YzRXQVJpYW5NZATJxR1BQVkNuZAHNwYnRpLXktSkhnWXlZANkowSgZDZD', max_length=500, verbose_name='Груп Access Token')),
                ('current_campaign', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pharmacist_campaign', to='campaign.Campaign', verbose_name='Идэвхтэй хөтөлбөр /Эмийн санч/')),
                ('current_campaign_beautician', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='beautician_campaign', to='campaign.Campaign', verbose_name='Идэвхтэй хөтөлбөр /Гоо сайханч/')),
            ],
            options={
                'verbose_name': 'Удирдлага',
                'verbose_name_plural': 'Удирдлага',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MonosMsgControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('control_name', models.CharField(default='Мессеж илгээх', max_length=200, verbose_name='Нэр')),
                ('content', models.CharField(blank=True, default='', max_length=640, null=True, verbose_name='Агуулга')),
                ('send_notification', models.BooleanField(default=False, verbose_name='Мэдэгдэл явуулах')),
                ('category', models.IntegerField(choices=[(0, 'Эмийн санч'), (1, 'Гоо сайханч')], default=0, verbose_name='Менежерийн төрөл')),
                ('managers', models.ManyToManyField(blank=True, to='receptmanager.ReceptManager', verbose_name='Хүлээн авагчид')),
            ],
            options={
                'verbose_name': 'Мессеж удирдлага',
                'verbose_name_plural': 'Мессеж удирдлага',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MonosMsgURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Гарчиг')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Тайлбар')),
                ('image_url', models.URLField(default='https://moilbot.monos.mn/media/monoso.jpeg', max_length=250, verbose_name='Зураг')),
                ('url', models.URLField(default='', max_length=250, verbose_name='Линк')),
                ('control', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='monoscontrol.MonosMsgControl', verbose_name='Мессеж удирдлага')),
            ],
            options={
                'verbose_name': 'Линк',
                'verbose_name_plural': 'Линкүүд',
            },
        ),
        migrations.CreateModel(
            name='WhiteListDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(default='', help_text='заавал http линк байх шаардлагатай', max_length=250, validators=[django.core.validators.URLValidator], verbose_name='Линк')),
            ],
            options={
                'verbose_name': 'Цагаан линк',
                'verbose_name_plural': 'Цагаан линкүүд',
            },
        ),
    ]
