# Generated by Django 2.0 on 2019-02-17 11:46

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(default='', help_text='Бүтэн нэр автоматаар үүснэ', max_length=100, verbose_name='Бүтэн нэр')),
                ('first_name', models.CharField(max_length=50, verbose_name='Нэр')),
                ('last_name', models.CharField(max_length=50, verbose_name='Овог')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Нэвтрэх нэр')),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Имэйл')),
                ('role', models.IntegerField(choices=[(0, 'Менежер'), (1, 'Хяналтын менежер')], default=0, verbose_name='Төрөл')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Утасны дугаар')),
                ('address', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Гэрийн хаяг')),
                ('facebook', models.CharField(blank=True, default='', max_length=80, verbose_name='Фэйсбүүк хаяг')),
                ('about', models.TextField(blank=True, default='', max_length=144, verbose_name='Тухай')),
                ('avatar', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Зураг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('manager_id', models.IntegerField(default=0, unique=True, verbose_name='Axis manager ID')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productmanagers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүний Менежер (PX)',
                'verbose_name_plural': 'Бүтээгдэхүүний Менежерүүд (PX)',
                'ordering': ['username'],
            },
        ),
    ]
